import { notFound } from "next/navigation";
import { BatteryCharging, CheckCircle2, Factory, Gauge, Leaf, MapPin, ShieldCheck, Wrench } from "lucide-react";

export default async function PassportPage({params}:{params:Promise<{serial:string}>}){
 const {serial}=await params;const match=/^PC4815-2027-(\d{6})$/.exec(serial);if(!match||Number(match[1])<1||Number(match[1])>10)notFound();
 const registry=`EU-DPP-DEMO-2027-${match[1]}`;
 return <main className="min-h-screen bg-slate-100 pb-14"><div className="bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-5 py-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-600 p-2"><BatteryCharging/></span><div><b>VoltRide Battery Passport</b><p className="text-xs text-slate-400">Публичное представление</p></div></div></div></div>
 <div className="mx-auto max-w-5xl px-5 pt-8"><div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Демонстрационный паспорт.</b> Он не является юридически действительным DPP и не зарегистрирован в реальном реестре ЕС.</div>
 <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-blue-700 to-slate-900 p-7 text-white shadow-xl sm:p-10"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-200">Цифровой паспорт батареи</p><h1 className="mt-4 text-4xl font-bold">PC-4815</h1><p className="mt-3 font-mono text-sm text-blue-100">{serial}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 backdrop-blur"><span className="flex items-center gap-2 text-sm font-semibold text-emerald-300"><CheckCircle2 size={18}/>Активен</span><p className="mt-2 text-xs text-blue-100">Dataset v1.0</p></div></div></section>
 <div className="mt-6 grid gap-5 md:grid-cols-3"><section className="card p-6 md:col-span-2"><h2 className="font-bold">Основная информация</h2><div className="mt-5 grid gap-x-7 gap-y-5 sm:grid-cols-2"><Info icon={<Factory/>} label="Производитель" value="Shenzhen PowerCell Technology Co., Ltd."/><Info icon={<MapPin/>} label="Место производства" value="Shenzhen, China"/><Info icon={<BatteryCharging/>} label="Категория" value="LMT"/><Info icon={<ShieldCheck/>} label="Дата производства" value="15.03.2027"/></div></section><section className="card p-6"><h2 className="font-bold">Демо-регистрация</h2><p className="mt-4 break-all font-mono text-sm text-blue-700">{registry}</p><span className="status mt-4 bg-emerald-50 text-emerald-700">DEMO REGISTERED</span><p className="mt-3 text-xs leading-5 text-slate-500">Вымышленный номер для демонстрации пользовательского сценария.</p></section></div>
 <section className="card mt-5 p-6"><h2 className="font-bold">Характеристики батареи</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Напряжение" value="48 V"/><Metric label="Ёмкость" value="15 Ah"/><Metric label="Энергия" value="720 Wh"/><Metric label="Химия" value="NMC"/><Metric label="Масса" value="3.6 kg"/></div></section>
 <div className="mt-5 grid gap-5 sm:grid-cols-2"><section className="card p-6"><div className="flex items-center gap-2 text-emerald-700"><Leaf size={20}/><h2 className="font-bold">Состав и устойчивость</h2></div><dl className="mt-4 space-y-3 text-sm"><Row k="Состав катода" v="NMC 811"/><Row k="Переработанный литий" v="12%"/><Row k="Конфигурация" v="13S5P"/></dl></section><section className="card p-6"><div className="flex items-center gap-2 text-blue-700"><Wrench size={20}/><h2 className="font-bold">Ремонт и демонтаж</h2></div><dl className="mt-4 space-y-3 text-sm"><Row k="Инструкция" v="DI-PC4815-v2"/><Row k="Запасная часть" v="PC4815-HOUSING-01"/><Row k="UN 38.3" v="UN38-PC4815-2026-118"/></dl></section></div>
 <p className="mt-8 text-center text-xs text-slate-500">Demo DPP Service · данные хранятся локально · версия 1.0</p></div></main>
}
function Info({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="flex gap-3"><span className="mt-0.5 text-blue-600">{icon}</span><div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div></div>}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><b className="mt-1 block text-xl">{value}</b></div>}
function Row({k,v}:{k:string,v:string}){return <div className="flex justify-between gap-4 border-b pb-2 last:border-0"><dt className="text-slate-500">{k}</dt><dd className="text-right font-semibold">{v}</dd></div>}
