"use client";
import { useEffect, useMemo, useState } from "react";
import { Archive, BarChart3, BatteryCharging, Check, CheckCircle2, ChevronRight, Clipboard, Download, ExternalLink, FileJson, FileSpreadsheet, FileText, FolderOpen, LayoutDashboard, Loader2, Mail, QrCode, RefreshCw, Send, ShieldCheck, Upload, X } from "lucide-react";
import QRCode from "qrcode";
import JSZip from "jszip";
import { demoDocuments } from "@/lib/demo-data";
import { buildDataset, DemoBatteryDataExtractor, DemoSupplierCommunicationService, LocalDppProvider, MockEuRegistryProvider } from "@/lib/services";
import { CanonicalBatteryField, DemoStage, DemoState, IndividualPassport, RawDocument } from "@/lib/types";
import { Badge } from "./Badge";
import { Workflow } from "./Workflow";
import { SourcePanel } from "./SourcePanel";

const extractor=new DemoBatteryDataExtractor(), communication=new DemoSupplierCommunicationService(), dpp=new LocalDppProvider(), registry=new MockEuRegistryProvider();
const initial:DemoState={stage:"documents",fields:[],analyzed:false,supplierRequestCreated:false,supplierRequestSent:false,supplierResponseReceived:false,supplierResponseParsed:false,conflictResolved:false,approvedDataset:null,passports:[]};
const stageIndex:Record<DemoStage,number>={documents:0,analysis:1,missing:2,approval:3,dataset:4,dpp:4,registry:5,qr:6,dashboard:7};

export function DemoApp(){
  const [state,setState]=useState<DemoState>(initial); const [hydrated,setHydrated]=useState(false); const [docs,setDocs]=useState<RawDocument[]>(demoDocuments); const [selected,setSelected]=useState<CanonicalBatteryField|null>(null);
  useEffect(()=>{const saved=localStorage.getItem("battery-passport-demo");if(saved)try{setState(JSON.parse(saved))}catch{}setHydrated(true)},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("battery-passport-demo",JSON.stringify(state))},[state,hydrated]);
  const update=(p:Partial<DemoState>)=>setState(s=>({...s,...p}));
  const reset=()=>{localStorage.removeItem("battery-passport-demo");setState(initial);setDocs(demoDocuments)};
  if(!hydrated)return null;
  return <div className="min-h-screen"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-8">
    <button onClick={()=>update({stage:"documents"})} className="flex items-center gap-3 text-left"><span className="rounded-xl bg-blue-600 p-2.5 text-white"><BatteryCharging/></span><span><b className="block text-lg">Battery Passport Demo</b><small className="text-slate-500">VoltRide Sp. z o.o.</small></span></button>
    <div className="flex items-center gap-3"><span className="hidden rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700 sm:block">Демонстрационная среда</span><button onClick={reset} className="btn-secondary"><RefreshCw size={15}/>Сбросить демо</button></div>
  </div></header><main className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8">
    <div className="mb-7"><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Battery Passport Demo</h1><p className="mt-1.5 text-slate-500">От документов поставщика до готового цифрового паспорта батареи</p></div>
    <Workflow active={stageIndex[state.stage]}/><div className="mt-6 grid gap-6 xl:grid-cols-[220px_1fr]"><Nav state={state} go={stage=>update({stage})}/><section className="min-w-0">
      {state.stage==="documents"&&<Documents docs={docs} setDocs={setDocs} onAnalyze={async()=>{update({stage:"analysis"})}}/>}
      {state.stage==="analysis"&&<Analysis state={state} update={update} docs={docs} select={setSelected}/>} 
      {state.stage==="missing"&&<Missing state={state} update={update}/>} 
      {state.stage==="approval"&&<Approval state={state} update={update} select={setSelected}/>} 
      {state.stage==="dataset"&&<Dataset state={state} update={update}/>} 
      {state.stage==="dpp"&&<Dpp state={state} update={update}/>} 
      {state.stage==="registry"&&<Registry state={state} update={update}/>} 
      {state.stage==="qr"&&<Qr state={state} update={update}/>} 
      {state.stage==="dashboard"&&<Dashboard state={state} update={update}/>} 
    </section></div>
  </main><SourcePanel field={selected} onClose={()=>setSelected(null)}/></div>
}

function Nav({state,go}:{state:DemoState,go:(s:DemoStage)=>void}){const items:[DemoStage,string,React.ReactNode][]=[["documents","Документы",<FolderOpen size={17}/>],["analysis","Результат анализа",<BarChart3 size={17}/>],["missing","Недостающие данные",<Mail size={17}/>],["approval","Проверка",<ShieldCheck size={17}/>],["dataset","Набор данных",<FileJson size={17}/>],["dpp","Demo DPP Service",<BatteryCharging size={17}/>],["registry","EU Registry",<Archive size={17}/>],["qr","QR-коды",<QrCode size={17}/>],["dashboard","Итоги",<LayoutDashboard size={17}/>]];
return <nav className="card h-fit p-2 xl:sticky xl:top-5">{items.map(([id,label,icon])=><button key={id} onClick={()=>go(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${state.stage===id?"bg-blue-50 font-semibold text-blue-700":"text-slate-600 hover:bg-slate-50"}`}>{icon}<span>{label}</span></button>)}</nav>}

function Heading({title,text}:{title:string,text:string}){return <div className="mb-5"><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>}

function Documents({docs,setDocs,onAnalyze}:{docs:RawDocument[],setDocs:(d:RawDocument[])=>void,onAnalyze:()=>void}){return <div><Heading title="Документы поставщика" text="Исходные файлы для батареи PowerCell PC-4815"/><div className="card overflow-hidden">
  <div className="border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Комплект документов · {docs.length} файлов</div>{docs.map(d=><div key={d.id} className="flex items-center justify-between border-b px-5 py-4 last:border-0"><div className="flex min-w-0 items-center gap-3"><span className="rounded-lg bg-blue-50 p-2 text-blue-600"><FileText size={18}/></span><div><p className="truncate text-sm font-semibold">{d.name}</p><p className="text-xs text-slate-500">{d.type} · {d.size}</p></div></div><div className="flex items-center gap-3"><span className="hidden items-center gap-1 text-xs font-semibold text-emerald-600 sm:flex"><Check size={14}/>Готов</span>{d.url&&<a href={d.url} download className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Download size={17}/></a>}</div></div>)}
  <label className="m-5 flex cursor-pointer items-center justify-center gap-3 rounded-xl border-2 border-dashed border-slate-200 px-5 py-6 text-sm font-semibold text-slate-600 hover:border-blue-300 hover:bg-blue-50/40"><Upload size={19}/>Загрузить свои файлы<input className="hidden" type="file" multiple accept=".pdf,.xlsx,.csv,.txt" onChange={e=>{const files=Array.from(e.target.files??[]);setDocs([...docs,...files.map((f,i)=>({id:`u${Date.now()}${i}`,name:f.name,type:f.name.split(".").pop()?.toUpperCase()??"FILE",size:`${Math.max(1,Math.round(f.size/1024))} КБ`}))])}}/></label>
  </div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Демо-режим: используется локальный механизм извлечения данных.</p><button onClick={onAnalyze} className="btn-primary">Проанализировать документы<ChevronRight size={17}/></button></div></div>}

function Analysis({state,update,docs,select}:{state:DemoState,update:(p:Partial<DemoState>)=>void,docs:RawDocument[],select:(f:CanonicalBatteryField)=>void}){
 const [running,setRunning]=useState(false);const [progress,setProgress]=useState(0);const phrases=["Чтение файлов...","Извлечение данных...","Сопоставление с Battery Passport...","Проверка источников...","Поиск отсутствующих данных...","Поиск противоречий..."];
 const analyze=async()=>{setRunning(true);for(let i=0;i<phrases.length;i++){setProgress(i+1);await new Promise(r=>setTimeout(r,300))}const fields=await extractor.extract(docs);update({fields,analyzed:true});setRunning(false)};
 if(!state.analyzed)return <div><Heading title="AI-анализ документов" text="Локальный Demo AI Engine извлекает, нормализует и сопоставляет значения"/><div className="card p-8 text-center"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-50 text-blue-600">{running?<Loader2 className="animate-spin" size={30}/>:<FileSearchIcon/>}</div><h3 className="text-lg font-bold">ИИ анализирует документы</h3><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">Без внешних API: распознавание выполняется детерминированными правилами внутри приложения.</p>{running&&<div className="mx-auto mt-6 max-w-md"><div className="mb-2 flex justify-between text-xs"><span>{phrases[Math.max(0,progress-1)]}</span><span>{Math.round(progress/phrases.length*100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600 transition-all" style={{width:`${progress/phrases.length*100}%`}}/></div></div>}<button disabled={running} onClick={analyze} className="btn-primary mt-6">{running?<Loader2 className="animate-spin" size={17}/>:<BarChart3 size={17}/>}Запустить анализ</button></div></div>;
 const found=state.fields.filter(f=>f.status==="FOUND").length,missing=state.fields.filter(f=>f.status==="MISSING").length,conflicts=state.fields.filter(f=>f.status==="CONFLICT").length;
 return <div><Heading title="Результат анализа: Battery PC-4815" text="Нажмите на любое значение, чтобы увидеть его источник"/><Stats readiness={72} values={[[found,"найдено"],[missing,"отсутствует"],[conflicts,"конфликт"],[3,"требуют подтверждения"]]}/><FieldTable fields={state.fields} select={select}/><div className="mt-5 flex justify-end"><button onClick={()=>update({stage:"missing"})} className="btn-primary">Работать с недостающими данными<ChevronRight size={17}/></button></div></div>
}
function FileSearchIcon(){return <BarChart3 size={30}/>}

function Stats({readiness,values}:{readiness:number,values:[number,string][]}){return <div className="card mb-5 p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="min-w-48"><div className="flex items-end justify-between"><span className="label">Готовность данных</span><b className="text-2xl text-blue-700">{readiness}%</b></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${readiness}%`}}/></div></div><div className="grid flex-1 grid-cols-2 gap-2 sm:grid-cols-4">{values.map(([n,l])=><div key={l} className="rounded-xl bg-slate-50 p-3"><b className="block text-xl">{n}</b><span className="text-xs text-slate-500">{l}</span></div>)}</div></div></div>}
function FieldTable({fields,select}:{fields:CanonicalBatteryField[],select:(f:CanonicalBatteryField)=>void}){return <div className="card overflow-hidden"><div className="field-row hidden bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500 lg:grid"><span className="col-span-3">Поле</span><span className="col-span-3">Значение</span><span className="col-span-3">Источник</span><span className="col-span-2">Статус</span><span className="col-span-1">Доступ</span></div>{fields.map(f=><button key={f.id} onClick={()=>select(f)} className="field-row w-full text-left text-sm"><span className="col-span-3 font-semibold">{f.name_ru}</span><span className="col-span-3 text-slate-700">{f.value??"—"} {f.unit}</span><span className="col-span-3 truncate text-xs text-blue-600">{f.sourceDocument??"Источник отсутствует"}</span><span className="col-span-2"><Badge status={f.status}/></span><span className="col-span-1 text-[10px] text-slate-400">{f.visibility}</span></button>)}</div>}

function Missing({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const missing=state.fields.filter(f=>f.status==="MISSING");const body=communication.createRequest(missing);const parse=async()=>{const data=await extractor.extractSupplierResponse();const fields=state.fields.map(f=>data[f.id]?{...f,value:data[f.id]!,status:"FOUND" as const,sourceDocument:"supplier_additional_data.xlsx",confidence:99,fragment:`${f.name_en}: ${data[f.id]}`} : f);update({fields,supplierResponseParsed:true})};
return <div><Heading title="Недостающие данные" text={state.supplierResponseParsed?"Ответ поставщика обработан; осталось разрешить конфликт массы":"4 обязательных поля требуют информации поставщика"}/><Stats readiness={state.conflictResolved?100:state.supplierResponseParsed?96:72} values={[[missing.length,"не заполнено"],[state.supplierResponseParsed?4:0,"получено"],[state.conflictResolved?0:1,"конфликт"],[1,"запрос поставщику"]]}/>
 {!state.supplierRequestCreated?<div className="card p-6"><h3 className="font-bold">Требуется уточнение у поставщика</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{missing.map(f=><div className="rounded-xl border p-4 text-sm font-semibold" key={f.id}>{f.name_ru}<span className="mt-1 block text-xs font-normal text-slate-500">Обязательное поле · {f.category}</span></div>)}</div><button onClick={()=>update({supplierRequestCreated:true})} className="btn-primary mt-5"><Mail size={17}/>Создать запрос поставщику</button></div>:<div className="space-y-5"><div className="card p-6"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Запрос поставщику</h3>{state.supplierRequestSent&&<span className="status bg-emerald-50 text-emerald-700">Запрос отправлен</span>}</div><pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-5 text-sm leading-6 text-slate-700">{body}</pre><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>navigator.clipboard?.writeText(body)} className="btn-secondary"><Clipboard size={16}/>Скопировать</button><button onClick={()=>downloadText("supplier_request.txt",body)} className="btn-secondary"><Download size={16}/>Скачать запрос</button><button disabled={state.supplierRequestSent} onClick={async()=>{await communication.simulateSend();update({supplierRequestSent:true})}} className="btn-primary"><Send size={16}/>Симулировать отправку</button></div></div>
 {state.supplierRequestSent&&!state.supplierResponseReceived&&<div className="card p-6"><h3 className="font-bold">Ожидается ответ поставщика</h3><p className="mt-1 text-sm text-slate-500">В демо ответ появляется по нажатию кнопки.</p><button onClick={()=>update({supplierResponseReceived:true})} className="btn-primary mt-4">Симулировать ответ поставщика</button></div>}
 {state.supplierResponseReceived&&<div className="card p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-600"><FileSpreadsheet/></span><div><h3 className="font-bold">Получен ответ поставщика</h3><a className="text-sm text-blue-600" href="/demo-documents/supplier_additional_data.xlsx" download>supplier_additional_data.xlsx</a></div></div>{!state.supplierResponseParsed?<button onClick={parse} className="btn-primary">Проанализировать ответ</button>:<span className="flex items-center gap-2 text-sm font-semibold text-emerald-600"><CheckCircle2 size={18}/>4 поля заполнены</span>}</div></div>}
 {state.supplierResponseParsed&&<Conflict state={state} update={update}/>}</div>}
 </div>}

function Conflict({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const [choice,setChoice]=useState("3.6");if(state.conflictResolved)return <div className="card border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-3 text-emerald-800"><CheckCircle2/><div><b>Данные готовы</b><p className="text-sm">Все обязательные поля заполнены, конфликт разрешён.</p></div></div><button onClick={()=>update({stage:"approval"})} className="btn-primary mt-4">Перейти к проверке<ChevronRight size={17}/></button></div>;
return <div className="card border-rose-200 p-6"><h3 className="font-bold text-rose-800">Разрешите конфликт массы</h3><p className="mt-1 text-sm text-slate-500">Источники содержат разные значения. Выберите подтверждённое значение.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["3.6","battery_datasheet.pdf"],["3.55","battery_specifications.xlsx"]].map(([v,s])=><label key={v} className={`cursor-pointer rounded-xl border-2 p-4 ${choice===v?"border-blue-500 bg-blue-50":"border-slate-200"}`}><input className="mr-2" type="radio" checked={choice===v} onChange={()=>setChoice(v)}/><b>Использовать {v} kg</b><span className="mt-1 block text-xs text-slate-500">Источник: {s}</span></label>)}</div><button onClick={()=>{const fields=state.fields.map(f=>f.id==="weight"?{...f,value:choice,status:"FOUND" as const,sourceDocument:choice==="3.6"?"battery_datasheet.pdf":"battery_specifications.xlsx",fragment:`Battery weight: ${choice} kg`}:f);update({fields,conflictResolved:true})}} className="btn-primary mt-4">Подтвердить</button></div>}

function Approval({state,update,select}:{state:DemoState,update:(p:Partial<DemoState>)=>void,select:(f:CanonicalBatteryField)=>void}){const [checked,setChecked]=useState(false);if(!state.conflictResolved)return <Gate text="Сначала заполните недостающие данные и разрешите конфликт." go={()=>update({stage:"missing"})}/>;return <div><Heading title="Проверка данных" text="Финальная проверка нормализованных полей человеком"/><FieldTable fields={state.fields.map(f=>({...f,status:state.approvedDataset?"APPROVED":f.status}))} select={select}/>{state.approvedDataset?<div className="card mt-5 border-emerald-200 bg-emerald-50 p-5"><b className="text-emerald-800">Набор данных утверждён · версия 1.0</b><p className="mt-1 text-sm text-emerald-700">{new Date(state.approvedDataset.approvedAt).toLocaleString("ru-RU")}</p><button onClick={()=>update({stage:"dataset"})} className="btn-primary mt-4">Открыть DPP-ready dataset</button></div>:<div className="card mt-5 p-5"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} className="h-4 w-4"/>Я подтверждаю, что проверил данные</label><button disabled={!checked} onClick={()=>update({approvedDataset:buildDataset(state.fields.map(f=>({...f,approved:true,status:"APPROVED"})))})} className="btn-primary mt-4"><ShieldCheck size={17}/>Утвердить набор данных</button></div>}</div>}

function Dataset({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){if(!state.approvedDataset)return <Gate text="Набор данных ещё не утверждён." go={()=>update({stage:"approval"})}/>;const json=JSON.stringify(state.approvedDataset,null,2);return <div><Heading title="DPP-ready dataset" text={`Версия ${state.approvedDataset.version} · зафиксирована ${new Date(state.approvedDataset.approvedAt).toLocaleString("ru-RU")}`}/><div className="card overflow-hidden"><div className="flex items-center justify-between border-b bg-slate-50 px-5 py-3"><span className="text-sm font-semibold">battery-passport-pc-4815-v1.0.json</span><span className="status bg-emerald-50 text-emerald-700">Утверждено</span></div><pre className="max-h-[520px] overflow-auto p-5 text-xs leading-6 text-slate-700">{json}</pre></div><div className="mt-4 flex flex-wrap justify-between gap-3"><div className="flex gap-2"><button onClick={()=>downloadText("battery-passport-pc-4815-v1.0.json",json,"application/json")} className="btn-secondary"><Download size={16}/>Скачать JSON</button><button onClick={()=>downloadText("battery-passport-pc-4815-v1.0.csv",fieldsCsv(state.fields),"text/csv") } className="btn-secondary"><Download size={16}/>Скачать CSV</button></div><button onClick={()=>update({stage:"dpp"})} className="btn-primary">Перейти в Demo DPP Service<ChevronRight size={17}/></button></div></div>}

function Dpp({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const [qty,setQty]=useState(10);if(!state.approvedDataset)return <Gate text="Сначала утвердите набор данных." go={()=>update({stage:"approval"})}/>;return <div><Heading title="Demo DPP Service" text="Локальный слой хостинга цифровых паспортов — внешняя платформа не используется"/><div className="card p-6"><div className="grid gap-5 md:grid-cols-2"><div><label className="label">Количество батарей</label><input min={1} max={10} type="number" value={qty} onChange={e=>setQty(Math.min(10,Math.max(1,+e.target.value)))} className="mt-2 w-full rounded-xl border px-4 py-3"/><p className="mt-2 text-xs text-slate-500">Для демо доступна партия до 10 единиц.</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="label mb-2">Серийные номера</p><p className="font-mono text-xs leading-6">PC4815-2027-000001<br/>…<br/>PC4815-2027-{String(qty).padStart(6,"0")}</p></div></div>{state.passports.length===0?<button onClick={async()=>update({passports:await dpp.createPassports(state.approvedDataset!,qty)})} className="btn-primary mt-5"><BatteryCharging size={17}/>Создать цифровые паспорта</button>:<div className="mt-5 flex items-center justify-between rounded-xl bg-emerald-50 p-4"><span className="flex items-center gap-2 font-semibold text-emerald-800"><CheckCircle2/>Создано паспортов: {state.passports.length}</span><button onClick={()=>update({stage:"registry"})} className="btn-primary">К регистрации<ChevronRight size={17}/></button></div>}</div></div>}

function Registry({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const [running,setRunning]=useState(false);const [logs,setLogs]=useState<string[]>([]);const registered=state.passports.filter(p=>p.registryStatus==="DEMO_REGISTERED").length;const run=async()=>{setRunning(true);const lines=["POST /demo-eu-registry/register","Checking economic operator...","Checking product identifier...","Checking passport location...","Validating dataset...","Registration successful."];for(const l of lines){setLogs(x=>[...x,l]);await new Promise(r=>setTimeout(r,250))}const records=await registry.register(state.passports);update({passports:state.passports.map(p=>{const r=records.find(x=>x.passportId===p.passportId)!;return {...p,registryStatus:"DEMO_REGISTERED",registryId:r.registrationId}})});setRunning(false)};if(!state.passports.length)return <Gate text="Сначала создайте цифровые паспорта." go={()=>update({stage:"dpp"})}/>;return <div><Heading title="Регистрация в EU Registry" text="Локальная симуляция интеграции для демонстрации процесса"/><div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><b>ДЕМО: реальный EU DPP Registry API не используется.</b><p className="mt-1">Все идентификаторы ниже вымышлены и не являются официальными регистрационными номерами ЕС.</p></div><div className="card p-6">{logs.length>0&&<div className="mb-5 rounded-xl bg-slate-950 p-5 font-mono text-xs leading-6 text-emerald-400">{logs.map(l=><div key={l}>{l}</div>)}</div>}{registered===0?<button disabled={running} onClick={run} className="btn-primary">{running?<Loader2 className="animate-spin" size={17}/>:<Archive size={17}/>}Зарегистрировать в EU Registry</button>:<><div className="flex items-center gap-3 text-emerald-700"><CheckCircle2/><b>{registered} регистраций выполнено — ДЕМО</b></div><div className="mt-4 max-h-64 overflow-auto rounded-xl border">{state.passports.map(p=><div key={p.passportId} className="flex justify-between border-b px-4 py-3 text-xs last:border-0"><span>{p.serialNumber}</span><b className="text-emerald-700">{p.registryId}</b></div>)}</div><button onClick={()=>update({stage:"qr"})} className="btn-primary mt-5">Создать QR-коды<ChevronRight size={17}/></button></>}</div></div>}

function Qr({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const [codes,setCodes]=useState<Record<string,string>>({});useEffect(()=>{if(state.passports.length&&typeof window!=="undefined")Promise.all(state.passports.map(async p=>[p.serialNumber,await QRCode.toDataURL(`${window.location.origin}${p.publicPassportUrl}`,{width:260,margin:1,color:{dark:"#172033",light:"#ffffff"}})] as const)).then(x=>setCodes(Object.fromEntries(x)))},[state.passports]);if(!state.passports.some(p=>p.registryStatus==="DEMO_REGISTERED"))return <Gate text="Сначала выполните демо-регистрацию." go={()=>update({stage:"registry"})}/>;const zip=async()=>{const z=new JSZip();for(const [serial,data] of Object.entries(codes))z.file(`${serial}.png`,data.split(",")[1],{base64:true});const blob=await z.generateAsync({type:"blob"});downloadBlob("battery-passport-qr-codes.zip",blob)};return <div><Heading title="QR-коды паспортов" text="Каждый код ведёт на уникальную публичную страницу внутри приложения"/><div className="mb-5 grid gap-3 sm:grid-cols-3"><MiniStat n={state.passports.length} l="паспортов создано"/><MiniStat n={state.passports.length} l="регистраций выполнено"/><MiniStat n={Object.keys(codes).length} l="QR-кодов готово"/></div><div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{state.passports.map((p,i)=><div className="card p-5" key={p.serialNumber}><div className="flex justify-between"><div><p className="label">Battery #{String(i+1).padStart(6,"0")}</p><h3 className="mt-1 font-semibold">{p.serialNumber}</h3><p className="mt-1 text-xs text-slate-500">{p.registryId}</p></div><span className="h-fit status bg-emerald-50 text-emerald-700">Готов</span></div>{codes[p.serialNumber]?<img alt={`QR ${p.serialNumber}`} className="mx-auto my-4 h-44 w-44" src={codes[p.serialNumber]}/>:<div className="mx-auto my-4 h-44 w-44 animate-pulse bg-slate-100"/>}<div className="flex gap-2"><a href={p.publicPassportUrl} target="_blank" className="btn-primary flex-1"><ExternalLink size={15}/>Открыть</a><button onClick={()=>downloadDataUrl(`${p.serialNumber}.png`,codes[p.serialNumber])} className="btn-secondary px-3"><Download size={16}/></button></div></div>)}</div><div className="mt-5 flex flex-wrap justify-between gap-3"><button disabled={Object.keys(codes).length!==state.passports.length} onClick={zip} className="btn-secondary"><Download size={17}/>Скачать все QR (ZIP)</button><button onClick={()=>update({stage:"dashboard"})} className="btn-primary">Открыть итоговый дашборд<ChevronRight size={17}/></button></div></div>}

function Dashboard({state,update}:{state:DemoState,update:(p:Partial<DemoState>)=>void}){const items=[["Документы поставщика","5 файлов"],["AI-анализ","23 поля"],["Недостающие данные","4 поля найдены"],["Ответ поставщика","получен"],["Проверка человеком","версия 1.0"],["Structured dataset","готов"],["DPP created",`${state.passports.length} паспортов`],["EU Registry demo",`${state.passports.length} записей`],["QR generated",`${state.passports.length} кодов`]];return <div><Heading title="VoltRide Sp. z o.o." text="Итоговый обзор демонстрационного жизненного цикла"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MiniStat n={1} l="модель батареи"/><MiniStat n={state.passports.length} l="физических батарей"/><MiniStat n={100} l="готовность данных, %"/><MiniStat n={1} l="запрос поставщику"/><MiniStat n={state.passports.length} l="паспортов"/><MiniStat n={state.passports.length} l="EU регистраций · DEMO"/><MiniStat n={state.passports.length} l="QR-кодов"/></div><div className="card mt-5 p-6"><h3 className="mb-5 font-bold">Полный жизненный цикл</h3><div className="grid gap-2 md:grid-cols-3">{items.map(([a,b],i)=><div key={a} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500 text-white"><Check size={14}/></span><div><b className="block text-sm">{a}</b><span className="text-xs text-slate-500">{b}</span></div></div>)}</div></div><div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm text-blue-900"><b>Демонстрация завершена.</b> Паспорта и регистрации созданы только локально и не имеют юридической силы.<div><button onClick={()=>update({stage:"qr"})} className="btn-primary mt-4">Открыть паспорта</button></div></div></div>}

function MiniStat({n,l}:{n:number,l:string}){return <div className="card p-4"><b className="text-2xl text-slate-900">{n}</b><p className="mt-1 text-xs text-slate-500">{l}</p></div>}
function Gate({text,go}:{text:string,go:()=>void}){return <div className="card p-8 text-center"><ShieldCheck className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 font-bold">Этап пока недоступен</h2><p className="mt-2 text-sm text-slate-500">{text}</p><button onClick={go} className="btn-primary mt-5">Вернуться к нужному этапу</button></div>}
function downloadText(name:string,text:string,type="text/plain"){downloadBlob(name,new Blob([text],{type}))}
function downloadBlob(name:string,blob:Blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function downloadDataUrl(name:string,url:string){if(!url)return;const a=document.createElement("a");a.href=url;a.download=name;a.click()}
function fieldsCsv(fields:CanonicalBatteryField[]){return "id,name_ru,value,unit,status,source\n"+fields.map(f=>[f.id,f.name_ru,f.value??"",f.unit??"",f.status,f.sourceDocument??""].map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")}
